# APIs bedienen (Lösung)

Wir machen nun die gleiche Abfrage wie vorhin, aber nutzen direkt die API.

In [4]:
import requests
import pandas as pd

In [11]:
url = "https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=2023-10-01&endtime=2023-10-04&orderby=magnitude&limit=10"

# Hier holen wir die Daten
response = requests.get(url)
data = response.json()

# Und nun sortieren wir nur das heraus, was uns interessiert
earthquakes = data['features']

final_list = []
for quake in earthquakes:
    magnitude = quake['properties']['mag']
    location = quake['properties']['place']
    latitude = quake['geometry']['coordinates'][1]
    longitude = quake['geometry']['coordinates'][0]
    depth = quake['geometry']['coordinates'][2]
    
    mini_dict = {"Magnitude": magnitude, 
                 "Location": location, 
                 "Latitude": latitude, 
                 "Longitude": longitude, 
                 "Depth": depth}
    
    final_list.append(mini_dict)

In [12]:
pd.DataFrame(final_list)

,Magnitude,Location,Latitude,Longitude,Depth
0,6.0,"Izu Islands, Japan region",29.9189,140.0172,10.000
1,5.8,"Izu Islands, Japan region",29.9105,140.0535,10.000
2,5.7,"158 km E of Kokopo, Papua New Guinea",-4.5206,153.6892,86.000
3,5.7,"40 km NE of Dipayal, Nepal",29.4987,81.2530,20.134
4,5.4,"24 km S of Goālpāra, India",25.9591,90.6152,10.000
5,5.3,"12 km S of Cicurug, Indonesia",-6.8967,106.7908,109.859
6,5.3,"48 km SSE of Karakenja, Tajikistan",38.8167,71.6851,13.617
7,5.3,"Bonin Islands, Japan region",28.3729,138.7811,517.010
8,5.2,"Izu Islands, Japan region",29.8376,140.1214,10.000
9,5.2,None,-57.0756,-30.1204,10.000